# "Name:" becomes the object for the Snakefile

# API key from fishair.org
Fish_AIR_API_Key: ""

# Input paths
File_Metadata: Files/Fish-AIR/Tulane/meta.xml
Image_Metadata: Files/Fish-AIR/Tulane/multimedia.csv
Image_Quality_Metadata: Files/Fish-AIR/Tulane/imageQualityMetadata.csv
Burress: Files/Previous Fish Measurements - Burress et al. 2016.csv

# Input settings
limit_images: 20 #if "" will run all, otherwise must input in integer

# Output paths
Minnow_Filtered: Results/minnow.filtered.from.iqm.csv
Burress_Minnow_Filtered: Results/burress.minnow.sp.filtered.from.iqm.csv
Sampling: Results/sampling.df.IQM.csv

DF_Missing_Scale: Results/df.missing.scale.csv
DF_Errors_Removed: Results/df.errors.removed.csv
Presence_Absence_Matrix: Results/presence.absence.matrix.csv
Sampling_Species_Burress: Results/sampling.species.in.Burress.csv
Sampling_Minnows_Seg: Results/sampling.minnows.95.blob.3.segments.csv
Sampling_DF_Seg: Results/sampling.df.seg.csv

Presence_Absence_Dist_Image: Results/presence.absence.sample.dist.png
Heatmap_Avg_Blob_Image: Results/heatmap.avg.blob.png
Heatmap_SD_Blob_Image: Results/heatmap.sd.blob.png
