# Input paths
Image_Metadata: Files/Image_Metadata_v1_20211206_151152.csv
Image_Quality_Metadata: Files/Image_Quality_Metadata_v1_20211206_151204.csv
Burress: Files/Previous Fish Measurements - Burress et al. 2016.csv

# Output paths
images_minnows: results/minnow.filtered.from.iqm.csv
burress_images_minnows: results/burress.minnow.sp.filtered.from.iqm.csv
