# Input paths
image_metadata: Files/Image_Metadata_v1_20211206_151152.csv
image_quality_metadata: Files/Image_Quality_Metadata_v1_20211206_151204.csv
burress: Previous Fish Measurements - Burress et al. 2016.csv

# Output paths
images_minnows: Files/minnow.filtered.from.imagequalitymetadata_25Jul2022.csv
burress_images_minnows: Files/burress.minnow.sp.filtered.from.imagequalitymetadata_25Jul2022.csv
