# "Name:" becomes the object for the Snakefile

# Input paths
Image_Metadata: Files/Image_Metadata_v1_20211206_151152.csv
Image_Quality_Metadata: Files/Image_Quality_Metadata_v1_20211206_151204.csv
Burress: Files/Previous Fish Measurements - Burress et al. 2016.csv

# Output paths
Minnow_Filtered: Results/minnow.filtered.from.iqm.csv
Burress_Minnow_Filtered: Results/burress.minnow.sp.filtered.from.iqm.csv
Sampling: Results/sampling.df.IQM.csv
