# "Name:" becomes the object for the Snakefile

# Input paths
Image_Metadata: Files/Image_Metadata_v1_20211206_151152.csv
Image_Metadata_DOI: doi:10.5072/FK2/QOHJGD
Image_Quality_Metadata: Files/Image_Quality_Metadata_v1_20211206_151204.csv
Image_Quality_Metadata_DOI: doi:10.5072/FK2/ZIFDTJ
Burress: Files/Previous Fish Measurements - Burress et al. 2016.csv
Burress_DOI: doi:10.5072/FK2/KLN3CS
limit_images: "" #if "" will run all, otherwise must input in integer

# Output paths
Minnow_Filtered: Results/minnow.filtered.from.iqm.csv
Burress_Minnow_Filtered: Results/burress.minnow.sp.filtered.from.iqm.csv
Sampling: Results/sampling.df.IQM.csv

Presence_Absence_Matrix: Results/presence.absence.matrix.csv
Sampling_Species_Burress: Results/sampling.species.in.Burress.csv
Sampling_Minnows_Seg: Results/sampling.minnows.95.blob.3.segments.csv
Sampling_DF_Seg: Results/sampling.df.seg.csv

Presence_Absence_Dist_Image: Results/presence.absence.sample.dist.png
Heatmap_Avg_Blob_Image: Results/heatmap.avg.blob.png
Heatmap_SD_Blob_Image: Results/heatmap.sd.blob.png
